### ISSUE TITLE
addPaymentType: Brand can be optional

### ISSUE THREAD

**Issue by wernerkrauss** [academe/omnipay-mpay24#8]
For giropay (german online banking), brand is set to "n/a" according to [mpay docs](https://docs.mpay24.com/docs/payment-systems), same  for maestro and paypal.

I suggest to make PurchaseRequest::addPaymentType()'s $brand parameter optional and only add to mdxi if set. Adding an empty brand results in an INVALID_MDXI error.

**Comment by judgej** [comment]
This should have been fixed by commit https://github.com/academe/omnipay-mpay24/commit/7e7c88ba0d7d33a9dcb962193092e994adb7545e a week ago. I've updated the documentation to go with it.

I'll close this issue for now, but if I have missed any places where the brand still appears to be mandatory, feel free to reopen.
